steps:
  build_image:
    image: quay.io/buildah/stable
    privileged: true
    environment:
      REGISTRY: harbor.anrostech.com
      IMAGE_BASE: anros/crm-back
      IMAGE_TAG: latest
      REGISTRY_USER:
        from_secret: registry_user
      REGISTRY_PASS:
        from_secret: registry_pass
    commands:
      - buildah login $REGISTRY -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

      # Pull previous images for cache
      - buildah pull $REGISTRY/$IMAGE_BASE-svc || true
      - buildah pull $REGISTRY/$IMAGE_BASE-nginx || true

      # Build both images in parallel
      - buildah build -f docker/svc/Dockerfile --cache-from $REGISTRY/$IMAGE_BASE-svc --layers --cache-to $REGISTRY/$IMAGE_BASE-svc -t $REGISTRY/$IMAGE_BASE-svc:$IMAGE_TAG . &
      - buildah build -f docker/nginx/Dockerfile --cache-from $REGISTRY/$IMAGE_BASE-nginx --layers --cache-to $REGISTRY/$IMAGE_BASE-nginx -t $REGISTRY/$IMAGE_BASE-nginx:$IMAGE_TAG . &
      - wait

      # Push both images in parallel
      - buildah push $REGISTRY/$IMAGE_BASE-svc:$IMAGE_TAG &
      - buildah push $REGISTRY/$IMAGE_BASE-nginx:$IMAGE_TAG &
      - wait

