steps:
  build_image:
    image: quay.io/podman/stable
    privileged: true
    environment:
      REGISTRY: harbor.anrostech.com
      IMAGE: harbor.anrostech.com/anros/crm-anros-backend:latest
    commands:
      - echo "Logging into Harbor..."
      - podman login $REGISTRY -u admin -p Harbor12345

      - echo "Building images via podman-compose..."
      - podman-compose -f docker-compose.yml build

      - echo "Pushing images via podman-compose..."
      - podman-compose -f docker-compose.yml push
